services:
  - type: web
    name: hoang-campaign-management
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=75.0"
